# Generated by Django 5.0.2 on 2024-03-04 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Category',
            fields=[
                ('Product_Category_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Product_Category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_id', models.IntegerField()),
                ('Product_name', models.CharField(max_length=100)),
                ('Product_brand', models.CharField(max_length=100)),
                ('Product_price', models.IntegerField()),
                ('Product_Category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product_category')),
            ],
        ),
    ]
